### ISSUE TITLE
How to extend a runtime with Deno?

### ISSUE THREAD

**Issue by gc-victor** [rscarson/rustyscript#20]
I want to extend a runtime with Deno extensions, as Rustyscript does with the features. For example, without using the web feature, I want to extend a runtime with deno_crypto.

**Comment by rscarson** [comment]
You can see an example using extensions [here](https://github.com/rscarson/rustyscript/blob/master/examples/runtime_extensions.rs)

Effectively you just need to pass `[extension_name::init_ops_and_esm()]` into the extensions parameter of RuntimeOptions

`deno_crypto` specifically, however, actually requires deno_web to work, which is why I couldn't expose that one as a feature

**Comment by rscarson** [comment]
Digging into the source for crypto, seems the culprit is `import DOMException from "ext:deno_web/01_dom_exception.js";`

I wonder if it would be possible to modify it to be able to use a fallback exception type if deno_web isn't available

**Comment by gc-victor** [comment]
I use extensions with my own JS to extend the runtime, and it works pretty well. The question is about extending it with Deno extensions. 

Let me be more specific. Why does this line work? How can I use it on an extension?

[`import * as crypto from "ext:deno_crypto/00_crypto.js";`](https://github.com/rscarson/rustyscript/blob/c97755a7f3bc57f53838da78d6009ef65c3234ee/src/ext/init_crypto.js#L1C1-L2C1)

**Comment by rscarson** [comment]
Oh I see what you mean now

In deno, importing from the 'ext:foo/bar.js' namespace will search for a a file within the extension you specify 

So for example, by default the deno_console extension is included, so you could use `import * as console from 'ext:deno_console/01_console.js';` and access its exports, for example `console.Console`, which I apply to global

rustyscript itself also has an extension I use for setting up the runtime; you'll notice my extension loaders all include something like `import { applyToGlobal, nonEnumerable } from 'ext:rustyscript/rustyscript.js';`

So that line you linked includes the stuff deno_crypto exports so that I can apply it to globalThis

That way you can just use `Crypto`, and not need to futz around with importing from extensions.

Are you having a specific issue getting crypto to run?

**Comment by gc-victor** [comment]
I can't add the Deno extensions the way you are adding them.
How the system gets the path `ext:deno_console/01_console.js` ?

**Comment by rscarson** [comment]
> I can't add the Deno extensions the way you are adding them. How the system gets the path `ext:deno_console/01_console.js` ?

You can - look at the example [here](https://github.com/rscarson/rustyscript/blob/master/examples/runtime_extensions.rs)

Internally, I just add any extensions you provide to the RuntimeOptions::extensions parameter to the list I add to the core

The path `ext:deno_console/01_console.js` tells the runtime to look for an file called `01_console.js` provided by an extension called `deno_console`

If you create your rustyscript Runtime with
```
    let mut runtime = Runtime::new(RuntimeOptions {
        extensions: vec![example_extension::example_extension::init_ops_and_esm()],
        ..Default::default()
    })?;
```

You have added an extension the same way I do internally, and get access to the files it adds

then, assuming `example_extension` adds a file called 01_example.js, you could import 
`ext:example_extension/01_example.js`

**Comment by gc-victor** [comment]
The issue is the import of the Deno JS file. How the system is getting that file? I can't do imports.

As you can see I'm adding extensions without any problem. 

https://github.com/gc-victor/query/blob/function/crates/server/src/runtime.rs#L33

**Comment by rscarson** [comment]
> The issue is the import of the Deno JS file. How the system is getting that file? I can't do imports.
> 
> As you can see I'm adding extensions without any problem.
> 
> https://github.com/gc-victor/query/blob/function/crates/server/src/runtime.rs#L33

What specifically are you trying to import and where? I don't see any imports in your extension JS

**Comment by gc-victor** [comment]
I have tried to do the same as you, import a Deno extension and it doesn't work.

**Comment by rscarson** [comment]
Can you show me what you tried? I don't think I understand your question

**Comment by rscarson** [comment]
I also don't see any deno extensions in that list

**Comment by gc-victor** [comment]
I have this error:

> called `Result::unwrap()` on an `Err` value: Specifier "ext:deno_crypto/00_crypto.js" was not passed as an extension module and was not included in the snapshot.

**Comment by rscarson** [comment]
You need to add the web feature to rustyscript - it will import the crypto extension for you

You can try to do it yourself by adding deno_crypto crate but deno_crypto needs deno_ web to run

**Comment by gc-victor** [comment]
> You need to add the web feature to rustyscript - it will import the crypto extension for you

It is what I was trying to avoid to maintain the sandboxing.

**Comment by gc-victor** [comment]
Thanks for the support and for this great crate!

**Comment by rscarson** [comment]
Thanks for your feedback!
I have an issue open with the deno team to try and get crypto to not depend on web

Though if you need it I could fork deno_crypto and try to make the changes in the form, if it works it could let you at least test it

**Comment by gc-victor** [comment]
The final goal was to personalize the runtime to match individual preferences.

**Comment by rscarson** [comment]
What other customizations would you like it to have?

**Comment by rscarson** [comment]
> The final goal was to personalize the runtime to match individual preferences.

Just to let you know, I just pushed a new version that enables the use of the crypto feature while preserving the sandbox :)

I did it by including a small polyfill extension that only provides the DomException class from deno_web, which activates if the web feature is disabled while crypto is in use
